FROM openjdk:17

WORKDIR /app

COPY target/MacedonianLegacy-0.0.1-SNAPSHOT.jar /app/MacedonianLegacy-0.0.1-SNAPSHOT.jar
EXPOSE 80
EXPOSE 8080

CMD ["java", "-jar", "MacedonianLegacy-0.0.1-SNAPSHOT.jar"]
